// 简化的Mock数据 - 为了测试兼容性
import type {
  DashboardStatsResponse,
  ModelRecommendationResponse,
  DatasetLatestResponse,
  CaseFeaturedResponse,
  CapabilityRecommendationResponse
} from '../../types/dashboard';

export const mockDashboardStats: DashboardStatsResponse = {
  totalModels: 12,
  totalDatasets: 89,
  totalCases: 234,
  totalCapabilities: 36,
  newModels: 3,
  newDatasets: 15,
  newCases: 42,
  newCapabilities: 8,
  activeModels: 10,
  publishedDatasets: 75,
  publishedCases: 189,
  onlineCapabilities: 32,
  totalUsers: 1567,
  totalViews: 23456,
  avgResponseTime: 1.2,
  availabilityRate: 98.5
};

export const mockModelRecommendations: ModelRecommendationResponse = {
  total: 3,
  list: [
    {
      id: '1',
      name: '数学大模型',
      code: 'math-model',
      description: '专注于数学问题解答和公式推导的AI模型',
      version: '2.1.0',
      type: 'llm',
      status: 'online',
      metrics: { accuracy: 97.8, perplexity: 5.2, inferenceSpeed: 1200 },
      framework: 'PyTorch',
      parameters: '12B',
      precision: 'FP16',
      fileSize: 25.6,
      category: '基础模型',
      tags: ['数学', '解题', '公式推导'],
      subjects: ['数学'],
      viewCount: 12345,
      downloadCount: 5678,
      rating: 4.8,
      createdAt: '2024-01-15 10:30:00',
      publishedAt: '2024-01-20 14:20:00'
    },
    {
      id: '2',
      name: '物理大模型',
      code: 'physics-model',
      description: '提供物理问题解析和实验指导的智能系统',
      version: '1.8.2',
      type: 'llm',
      status: 'online',
      metrics: { accuracy: 96.5, perplexity: 6.1, inferenceSpeed: 980 },
      framework: 'TensorFlow',
      parameters: '8B',
      precision: 'FP32',
      fileSize: 18.9,
      category: '基础模型',
      tags: ['物理', '实验', '问题解析'],
      subjects: ['物理'],
      viewCount: 9876,
      downloadCount: 4321,
      rating: 4.6,
      createdAt: '2024-02-01 09:15:00',
      publishedAt: '2024-02-05 16:45:00'
    },
    {
      id: '3',
      name: '化学大模型',
      code: 'chemistry-model',
      description: '化学方程式计算和实验数据分析的AI助手',
      version: '1.5.1',
      type: 'llm',
      status: 'offline',
      metrics: { accuracy: 95.2, perplexity: 7.3, inferenceSpeed: 850 },
      framework: 'PyTorch',
      parameters: '6B',
      precision: 'FP16',
      fileSize: 15.2,
      category: '基础模型',
      tags: ['化学', '方程式', '实验数据'],
      subjects: ['化学'],
      viewCount: 7654,
      downloadCount: 3456,
      rating: 4.4,
      createdAt: '2024-01-20 11:00:00',
      publishedAt: '2024-01-25 10:30:00'
    }
  ]
};

export const mockDatasetLatest: DatasetLatestResponse = {
  total: 3,
  list: [
    {
      id: '1',
      name: '数学题库',
      code: 'math-dataset',
      description: '包含10万+数学题目的标准化题库',
      version: '3.2.0',
      format: 'json',
      status: 'published',
      size: 256,
      sampleCount: 120450,
      tokenCount: 1560000,
      languages: ['中文'],
      difficulty: 'advanced',
      qualityScore: 92.5,
      category: '题库',
      tags: ['数学', '题目', '标准化'],
      subjects: ['数学'],
      viewCount: 5678,
      downloadCount: 2345,
      createdAt: '2024-01-05 14:20:00',
      publishedAt: '2024-01-10 09:15:00'
    },
    {
      id: '2',
      name: '物理实验数据',
      code: 'physics-dataset',
      description: '物理实验测量数据和分析报告',
      version: '1.0.1',
      format: 'csv',
      status: 'published',
      size: 156,
      sampleCount: 89230,
      tokenCount: 987600,
      languages: ['中文'],
      difficulty: 'intermediate',
      qualityScore: 88.3,
      category: '实验数据',
      tags: ['物理', '实验', '数据'],
      subjects: ['物理'],
      viewCount: 4321,
      downloadCount: 1890,
      createdAt: '2024-01-10 09:30:00',
      publishedAt: '2024-01-15 14:10:00'
    },
    {
      id: '3',
      name: '化学元素周期表',
      code: 'chemistry-periodic-table',
      description: '包含所有化学元素信息和性质的结构化知识库',
      version: '2.0.0',
      format: 'json',
      status: 'reviewing',
      size: 45,
      sampleCount: 2350,
      tokenCount: 56780,
      languages: ['中文', '英文'],
      difficulty: 'beginner',
      qualityScore: 95.0,
      category: '知识库',
      tags: ['化学', '元素', '周期表'],
      subjects: ['化学'],
      viewCount: 2345,
      downloadCount: 892,
      createdAt: '2024-02-15 16:10:00',
      publishedAt: '2024-02-20 10:45:00'
    }
  ]
};

export const mockCaseFeatured: CaseFeaturedResponse = {
  total: 3,
  list: [
    {
      id: '1',
      title: '高三数学总复习',
      code: 'math-review',
      summary: '针对高三数学总复习的AI辅助教学案例',
      scenario: '教学应用',
      category: '教学',
      tags: ['数学', '高三', '复习', 'AI辅助'],
      subjects: ['数学'],
      relatedModels: ['数学大模型'],
      relatedDatasets: ['数学题库'],
      relatedCapabilities: ['智能答题', '公式识别'],
      viewCount: 1234,
      likeCount: 567,
      bookmarkCount: 234,
      status: 'published',
      difficulty: 'advanced',
      duration: 120,
      steps: 8,
      author: '张三',
      organization: 'XX中学',
      createdAt: '2024-01-20 14:30:00',
      publishedAt: '2024-01-25 11:20:00'
    },
    {
      id: '2',
      title: '物理实验数据分析',
      code: 'physics-analysis',
      summary: '利用AI分析物理实验数据的应用案例',
      scenario: '实验分析',
      category: '实验',
      tags: ['物理', '实验', '数据分析', 'AI'],
      subjects: ['物理'],
      relatedModels: ['物理大模型'],
      relatedDatasets: ['物理实验数据'],
      relatedCapabilities: ['数据分析'],
      viewCount: 892,
      likeCount: 345,
      bookmarkCount: 156,
      status: 'pending',
      difficulty: 'intermediate',
      duration: 90,
      steps: 6,
      author: '李四',
      organization: 'YY中学',
      createdAt: '2024-02-01 11:15:00',
      publishedAt: '2024-02-05 09:45:00'
    },
    {
      id: '3',
      title: '化学方程式学习',
      code: 'chemistry-equations',
      summary: '化学方程式自动配平教学系统',
      scenario: '智能学习',
      category: '学习',
      tags: ['化学', '方程式', '自动配平', '教学'],
      subjects: ['化学'],
      relatedModels: ['化学大模型'],
      relatedDatasets: ['化学元素周期表'],
      relatedCapabilities: ['智能答题'],
      viewCount: 654,
      likeCount: 234,
      bookmarkCount: 98,
      status: 'draft',
      difficulty: 'beginner',
      duration: 60,
      steps: 5,
      author: '王五',
      organization: 'ZZ中学',
      createdAt: '2024-02-28 09:45:00',
      publishedAt: '2024-03-01 14:10:00'
    }
  ]
};

export const mockCapabilityRecommendations: CapabilityRecommendationResponse = {
  total: 3,
  list: [
    {
      id: '1',
      name: '智能答题',
      code: 'intelligent-answering',
      description: '提供各类学科问题的智能解答和分析',
      category: 'question_answering',
      subCategory: '问题解答',
      tags: ['智能答题', '问题解答', 'AI'],
      subjects: ['数学', '物理', '化学'],
      avgResponseTime: 1.2,
      availability: 98.5,
      rateLimit: 100,
      isFeatured: true,
      status: 'online',
      icon: '🎯',
      sortOrder: 1,
      usageCount: 12345,
      successRate: 97.8,
      apiEndpoint: '/api/v1/answer',
      apiMethod: 'POST',
      viewCount: 5678,
      trialCount: 2345,
      rating: 4.8,
      createdAt: '2024-01-10 10:30:00',
      updatedAt: '2024-03-02 11:15:00'
    },
    {
      id: '2',
      name: '公式识别',
      code: 'formula-recognition',
      description: '识别和解析数学公式的图像识别功能',
      category: 'multimodal',
      subCategory: '公式识别',
      tags: ['公式识别', '图像识别', '数学'],
      subjects: ['数学'],
      avgResponseTime: 0.8,
      availability: 95.2,
      rateLimit: 80,
      isFeatured: true,
      status: 'online',
      icon: '🧪',
      sortOrder: 2,
      usageCount: 8765,
      successRate: 96.3,
      apiEndpoint: '/api/v1/recognize-formula',
      apiMethod: 'POST',
      viewCount: 4321,
      trialCount: 1890,
      rating: 4.7,
      createdAt: '2024-01-15 14:20:00',
      updatedAt: '2024-02-28 15:40:00'
    },
    {
      id: '3',
      name: '数据分析',
      code: 'data-analysis',
      description: '对实验数据进行统计分析和可视化展示',
      category: 'text_analysis',
      subCategory: '统计分析',
      tags: ['数据分析', '统计分析', '可视化'],
      subjects: ['物理', '化学'],
      avgResponseTime: 2.5,
      availability: 92.8,
      rateLimit: 50,
      isFeatured: false,
      status: 'developing',
      icon: '📊',
      sortOrder: 3,
      usageCount: 3456,
      successRate: 91.5,
      apiEndpoint: '/api/v1/analyze-data',
      apiMethod: 'POST',
      viewCount: 2345,
      trialCount: 892,
      rating: 4.5,
      createdAt: '2024-02-01 09:15:00',
      updatedAt: '2024-03-01 16:20:00'
    }
  ]
};
